INSERT INTO genre (id, name) VALUES (1, 'Fantasy');
INSERT INTO genre (id, name) VALUES (2, 'Adventure');
INSERT INTO genre (id, name) VALUES (3, 'Romance');
INSERT INTO genre (id, name) VALUES (4, 'Contemporary');
INSERT INTO genre (id, name) VALUES (5, 'Dystopian');
INSERT INTO genre (id, name) VALUES (6, 'Mystery');
INSERT INTO genre (id, name) VALUES (7, 'Horror');
INSERT INTO genre (id, name) VALUES (8, 'Thriller');
INSERT INTO genre (id, name) VALUES (9, 'Paranormal');
INSERT INTO genre (id, name) VALUES (10, 'Historical fiction');
INSERT INTO genre (id, name) VALUES (11, 'Science Fiction');
INSERT INTO genre (id, name) VALUES (12, 'Memoir');
INSERT INTO genre (id, name) VALUES (13, 'Cooking');
INSERT INTO genre (id, name) VALUES (14, 'Art');
INSERT INTO genre (id, name) VALUES (15, 'Personal');
INSERT INTO genre (id, name) VALUES (16, 'Development');
INSERT INTO genre (id, name) VALUES (17, 'Motivational');
INSERT INTO genre (id, name) VALUES (18, 'Health');
INSERT INTO genre (id, name) VALUES (19, 'History');
INSERT INTO genre (id, name) VALUES (20, 'Travel');
INSERT INTO genre (id, name) VALUES (20, 'Guides');
INSERT INTO genre (id, name) VALUES (21, 'Families & Relationships');
INSERT INTO genre (id, name) VALUES (22, 'Humor');
INSERT INTO genre (id, name) VALUES (23, 'Children');